---
- name: Docker Pull of Calculator App
  hosts: all
  # become: yes
  vars:
    - image: madhav022/calculator
  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started
    
    - name: Docker Pull
      docker_image:
        name: '{{image}}'
        source: pull
      
    - name: Docker Run
      command: docker run -it --name Calculator_app {{image}}
      register: output

    - name: Docker Output
      debug:
        msg: '{{output.stdout_lines}}
        {{output.stdout}}'