---
- name: Docker Pull of Calculator App
  hosts: all
  vars:
      - image: madhav022/calculator
  tasks:
      - name: Start Docker Service
        service:
            name: docker
            state: started

      - name: Docker Pull
        docker_image:
            name: '{{image}}'
            source: pull

      - name: Removing Old Docker Images & Containers
        command: docker image prune -f && docker container prune -f
        register: output

      - name: Display Docker Images Removed
        debug:
          msg: '{{output.stdout}}'

      - name: Docker Run
        command: docker create -it --name Calculator_app {{image}}
        register: output

      - name: Docker Container Creation Output
        debug:
          msg: '{{output.stdout}}'
