---
- name: Deployment of Calculator App
  hosts: all
  vars:
      - image: madhav022/calculator
  tasks:
      - name: Start Docker Service
        service:
            name: docker
            state: started

      - name: Docker Pull
        docker_image:
            name: '{{image}}'
            source: pull

      - name: Docker Images
        command: docker images
        register: output
      
      - name: Display Images
        debug:
          msg: '{{output.stdout}}'

      - name: Removing Old Docker Containers
        command: docker container prune -f
        register: output

      - name: Display Docker Containers Removed
        debug:
          msg: '{{output.stdout}}'

      - name: Removing Old Docker Images
        command: docker image prune -f
        register: output

      - name: Display Docker Images Removed
        debug:
          msg: '{{output.stdout}}'

      - name: Docker Run
        command: docker create -it --name Calculator_app {{image}}
        register: output

      - name: Docker Container Creation Output
        debug:
          msg: Docker Container Created ID:'{{output.stdout}}'
